var config = {
	"dev": {
	  SERVER_URL: "http://49.232.8.38:84/",
	  AD_UNIT_ID: "ca-app-pub-3940256099942544/5224354917",
	  ENABLE_GOOGLEPLAY_CHECK: false,
	  ENABLE_GM: true,
	  APP_LOCATION: 1,
	  //SHOW_DEBUG: true,
	  NET_LOG:true,
	  HOTUPDATE_TAG:"_dev",
	  EXCEL_DIR:"excel_dev",
	  ALLOW_HOTUPDATE: true,//测试包热更和微信版热更冲突 暂时关闭
	  VERSION_NAME_TAG: "t",
	 },
	 "global": {
	  ALLOW_HOTUPDATE: true,
	  SHOW_DEBUG: false,
	  DEBUG_FIX_GUEST_ID: 0,
	  DEBUG_FIX_STAGE_LEVEL: 0,
	  DEBUG_FIX_TUTOR_STEP: 0,
	  ENABLE_TUTORIAL: true,
	  ENABLE_NET: true,
	  ENABLE_ROBOT: false,
	  SERVER_URL: "https://global.gardendoggame.com/",
	  ENABLE_EVENT_LOG: true,
	  ENABLE_GM: false,
	  DEBUG_FAST_WIN_GOLD: 0,
	  UNLOCK_ALL_RESTAURANT: false,
	  AD_UNIT_ID: "ca-app-pub-8730545242333031/9736063955",
	  SDK_TYPE:'google_play',
	  ENABLE_GOOGLEPLAY_CHECK:false,
	  APP_LOCATION: 1,
	  ENABLE_ACTION_LOG:false,
	  PAY_SERVER:null,
	  HOTUPDATE_TAG:"",
	  EXCEL_DIR:"excel",
	  VERSION_NAME_TAG: "",
	  ENBALE_MOBILE_PHONE_BINDDING:false,
	 },
	 "ph": {
	  ALLOW_HOTUPDATE: true,
	  SHOW_DEBUG: false,
	  DEBUG_FIX_GUEST_ID: 0,
	  DEBUG_FIX_STAGE_LEVEL: 0,
	  DEBUG_FIX_TUTOR_STEP: 0,
	  ENABLE_TUTORIAL: true,
	  ENABLE_NET: true,
	  ENABLE_ROBOT: false,
	  SERVER_URL: "https://ph.gardendoggame.com/",
	  ENABLE_EVENT_LOG: true,
	  ENABLE_GM: false,
	  DEBUG_FAST_WIN_GOLD: 0,
	  UNLOCK_ALL_RESTAURANT: false,
	  AD_UNIT_ID: "ca-app-pub-8730545242333031/9736063955",
	  SDK_TYPE:'google_play',
	  ENABLE_GOOGLEPLAY_CHECK:false,
	  APP_LOCATION: -1,
	  ENABLE_ACTION_LOG:false,
	  PAY_SERVER:null,
	  HOTUPDATE_TAG:"_PH",
	  EXCEL_DIR:"excel",
	  VERSION_NAME_TAG: "b",
	  ENBALE_MOBILE_PHONE_BINDDING:false,
	 },
	 "wx": {
	  ALLOW_HOTUPDATE: true,
	  SHOW_DEBUG: false,
	  DEBUG_FIX_GUEST_ID: 0,
	  DEBUG_FIX_STAGE_LEVEL: 0,
	  DEBUG_FIX_TUTOR_STEP: 0,
	  ENABLE_TUTORIAL: true,
	  ENABLE_NET: true,
	  ENABLE_ROBOT: false,
	  SERVER_URL: "https://webq.gardendoggame.com/",
	  ENABLE_EVENT_LOG: true,
	  ENABLE_GM: false,
	  DEBUG_FAST_WIN_GOLD: 0,
	  UNLOCK_ALL_RESTAURANT: false,
	  AD_UNIT_ID: "ca-app-pub-8730545242333031/9736063955",
	  SDK_TYPE:'google_play',
	  ENABLE_GOOGLEPLAY_CHECK:false,
	  APP_LOCATION: 1,
	  ENABLE_ACTION_LOG:false,
	  PAY_SERVER:null,
	  HOTUPDATE_TAG:"_WX",
	  EXCEL_DIR:"excel",
	  VERSION_NAME_TAG: "w",
	  ENBALE_MOBILE_PHONE_BINDDING:true,
	 }
}

module.exports = config;